# https://github.com/chriskempson/base16-xresources/blob/master/base16-ashes.dark.256.xresources
# Base16 Ashes
# Scheme: Jannik Siebert (https://github.com/janniks)
foreground=#f0f0f5
background=#000000
cursor=#ff1a67

color0=#181818
color1=#ff1a67
color2=#42ff97
color3=#7c60d1
color4=#29adff
color5=#fd007f
color6=#00a8a4
color7=#505050
color8=#252525
color9=#ff004b
color10=#42ffad
color11=#fd7cff
color12=#c7b8ff
color13=#fd0098
color14=#00fff9
color15=#e7e7e7
